In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Customer-Churn-Records.csv')
df.head()

,Row Number,Customer Id,Surname,Credit Score,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Cr Card,Is Active Member,Estimated Salary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row Number          10000 non-null  int64
 1   Customer Id         10000 non-null  int64
 2   Surname             10000 non-null  object
 3   Credit Score        10000 non-null  int64
 4   Geography           10000 non-null  object
 5   Gender              10000 non-null  object
 6   Age                 10000 non-null  int64
 7   Tenure              10000 non-null  int64
 8   Balance             10000 non-null  float64
 9   Num Of Products     10000 non-null  int64
 10  Has Cr Card         10000 non-null  int64
 11  Is Active Member    10000 non-null  int64
 12  Estimated Salary    10000 non-null  float64
 13  Exited              10000 non-null  int64
 14  Complain            10000 non-null  int64
 15  Satisfaction Score  10000 non-null  int64
 16  Card Type           10000 non-null  object
 17  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(12), object(4)
memory usage: 1.4+ MB

In [4]:
df.describe()

,Row Number,Customer Id,Credit Score,Age,Tenure,Balance,Num Of Products,Has Cr Card,Is Active Member,Estimated Salary,Exited,Complain,Satisfaction Score,Point Earned
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203800,0.204400,3.013800,606.515100
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402842,0.403283,1.405919,225.924839
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,1.000000,119.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,2.000000,410.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,3.000000,605.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,0.000000,4.000000,801.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,5.000000,1000.000000

In [5]:
df.describe(include='all')

,Row Number,Customer Id,Surname,Credit Score,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Cr Card,Is Active Member,Estimated Salary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
count,10000.00000,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000,10000.000000
unique,NaN,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN
top,NaN,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DIAMOND,NaN
freq,NaN,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2507,NaN
mean,5000.50000,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203800,0.204400,3.013800,NaN,606.515100
std,2886.89568,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402842,0.403283,1.405919,NaN,225.924839
min,1.00000,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,1.000000,NaN,119.000000
25%,2500.75000,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,2.000000,NaN,410.000000
50%,5000.50000,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,3.000000,NaN,605.000000
75%,7500.25000,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,0.000000,4.000000,NaN,801.000000
max,10000.00000,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,5.000000,NaN,1000.000000

In [6]:
df.isnull().sum()

Row Number            0
Customer Id           0
Surname               0
Credit Score          0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
Num Of Products       0
Has Cr Card           0
Is Active Member      0
Estimated Salary      0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

In [7]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ', '_')

In [8]:
df.columns

Index(['row_number', 'customer_id', 'surname', 'credit_score', 'geography',
       'gender', 'age', 'tenure', 'balance', 'num_of_products', 'has_cr_card',
       'is_active_member', 'estimated_salary', 'exited', 'complain',
       'satisfaction_score', 'card_type', 'point_earned'],
      dtype='object')

In [9]:
df=df.drop(columns=['row_number', 'surname'])

In [10]:
labels=['Poor', 'Average', 'Good', 'Excellent']
df['credit_score_range']=pd.qcut(df['credit_score'], 4, labels=labels)

In [11]:
df[['credit_score', 'credit_score_range']].head(10)

   credit_score credit_score_range
0           619            Average
1           608            Average
2           502               Poor
3           699               Good
4           850          Excellent
5           645            Average
6           822          Excellent
7           376               Poor
8           501               Poor
9           684               Good

In [12]:
age_groups=['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group']=pd.qcut(df['age'], 4, labels=age_groups)

In [13]:
df[['age', 'age_group']].head(10)

   age    age_group
0   42  Middle-Aged
1   41  Middle-Aged
2   42  Middle-Aged
3   39  Middle-Aged
4   43  Middle-Aged
5   44  Middle-Aged
6   50       Senior
7   29  Young Adult
8   44  Middle-Aged
9   27  Young Adult

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [18]:
from sqlalchemy import create_engine

username='postgres'
password='root'
host='localhost'
port='5432'
database='BankingAnalysis'

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="customerchurn"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data loaded into table '{table_name}' in database '{database}'")

Data loaded into table 'customerchurn' in database 'BankingAnalysis'